#print("Hello World!")
#print("Hello Again")
#print("I like this typing this.")
#print("This is fun")
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
#print("I am practcing writing one more script")
#print("This is 'one' more, maybe 'two' more")
print("This is my attempt to only print one line")
print("Just doing more printing practice")
print('Like this line is cool and all')
print('What do "YOU" think?')
print("Should I do 20 lines like the pwd practice")
print("I am stopping at '15'")
